<br>
<br>

## Civic Engagement


I am deeply passionate about clean water issues and more broadly the well-being of my fellow humans. Environmental and social justice are tightly entertwined, and I support causes that bring a better quality of life for all human and non-human beings. 

There are many excellent causes to support, and sometimes it feels overwhelming to understand where to focus my time and energy. I have spent my time recently facilitating community dialogue around the competing water uses in Montana. I have also gotten involved in organizing panel discussions featuring women in science roles.

Prior to moving to Montana, I worked with middle school-aged girls at a water quality camp and helped to organize campus lectures about carbon tax legislation in Washington. For a full description of the projects I have been involved with please see my CV. 


If you have a project involving environmental quality that could use support, data analysis, ideas, or a listening ear, please send me an email! 