<br>
<br>

### Resume

##### [Resume](/resume.pdf)

<br>

### Select Experience

#### Reports & Contributions

Losi, C. (2024). McIsaac Ranch Land Exchange Draft Environmental Assessment. Contribution to environmental assessment for Flowra. (In Progress)

Perkins, K. R., & Kann, J. (2024). A Review of Best Practices for Controlling Agricultural Nonpoint Source Pollution in Oregon. Literature review prepared for Trout Unlimited and Wild Salmon Center.

Perkins, K. R., & Kann, J. (2024). Compilation and Assessment of Bear Creek Water Quality Data Collected After the Almeda Drive Fire. Technical Memorandum prepared for Rogue Valley Council of Governments

Losi, C. (2023). Notice of Intent and Instructions for Category 5A, USFS Post-Fire Activities for North Quincy Wildfire Resiliency Project. Contribution to NOI for Central Valley Regional Water Quality Control Board. 

Losi, C. (2023). North Quincy Wildfire Resiliency Project Environmental Assessment. Contribution to environmental assessment for Alta Bally Consulting.

Perkins, K. R., & Asarian, J. E. (2023). State of the Basin: Scott River. Water quality report card prepared for: Klamath Tribal Water Quality Consortium.

Asarian, J. E., Kann, J., & Perkins, K. (2023). Temperature Dynamics and Trends in Upper Klamath Basin Tributaries: Assessment of The Klamath Tribes Long-Term Thermograph Monitoring Program. Contribution to report prepared for the Klamath Tribes.

Perkins, K. R. (2023). Klamath Basin 6PPD-quinone Sampling Analysis Plan for the Klamath Tribal Water Quality Consortium.

Kann, J., & Perkins, K. (2021). Upper Klamath Lake 2021 Data Summary Report. Report prepared for Klamath Tribes.

Kann, J., & Perkins, K. (2021). Upper Klamath Lake 2020 Data Summary Report. Report prepared for Klamath Tribes.

Perkins, K. R. (2021). Concentration and composition of nanoparticles and colloidal particles in a mine-waste contaminated river. Master’s thesis at the University of Montana.

Publication

Perkins, K. R., Rollwagen-Bollens, G., Bollens, S. M., & Harrison, J. A. (2019). Variability in the vertical distribution of chlorophyll in a spill-managed temperate reservoir. Lake and Reservoir Management, 35, 119–126.

#### Field-based data collection

Snorkel surveys of algae and macrophyte communities on the Klamath River. 2021 – present (ongoing). Data collected for the Klamath Tribal Water Quality Consortium and Dr. Laurel Genzoli, University of Montana. 

Significant existing or potential erosion sites (SEPES) and road haul data collection, Plumas National Forest. Data collected for North Quincy Wildfire Resiliency Project with The Flowra Platform consulting. 

Upper Clark Fork River metals monitoring and colloidal metal particle research in a mine-waste contaminated river. (2017-2020). Data collected for the Ecosystems Lab, University of Montana laboratory data and master’s thesis research.

Lacamas Lake monitoring and study of planktonic organisms and water quality parameters before and after reservoir drawdown, assistant for: field sampling for planktonic organisms in greater Columbia River Basin, laboratory-based invasive clam feeding rate study. (2014-2017). Data collected for the Aquatic Ecology Lab, Washington State University Vancouver laboratory data and undergraduate thesis research.



